doc-warnings: false
test-warnings: true
strictness: medium
max-line-length: 79
ignore-patterns:
    - ^build
    - ^impala/_thrift_gen
    - ^examples
    - _dbapi20_tests.py
    - ez_setup.py
    - scratch.py
    - ^udf-scratch
